### PR TITLE
Prevent error when plugin watcher has invalid email; fixes #75

### LINKED ISSUE #75: Error during alerts sending to plugins watchers
When plugins watchers alerts are sent after a plugin XML update, an error may occurs if a watcher email address is invalid.
It breaks the loop, and following watchers are not alerted.

```
PHP Fatal error:  Uncaught Swift_RfcComplianceException: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. in /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:345
Stack trace:
#0 /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(261): Swift_Mime_Headers_MailboxHeader->_assertValidAddress()
#1 /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes()
#2 /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses()
#3 /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel()
#4 /var/www/plugins.glpi-project.org/api/vendor/swiftmailer in /var/www/plugins.glpi-project.org/api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php on line 345
```

### PR DESCRIPTION
**Pull request by cedric-anne**

### CODE REVIEW

File: api/src/core/BackgroundTasks.php [hunk 1]
```diff
@@ -487,9 +487,13 @@ private function updatePlugin($plugin, $index = null, $length = null, $subtasks)
    }
 
    private function alertWatchers($plugin) {
-      $client_url = Tool::getConfig()['client_url'];
+      $mime_grammar = new \Swift_Mime_Grammar();
+
       foreach ($plugin->watchers()->get() as $watch) {
          $user = $watch->user;
+         if (!preg_match('/^'.$mime_grammar->getDefinition('addr-spec').'$/D', $user->email)) {
```
Comment (cedric-anne) [inline api/src/core/BackgroundTasks.php:494]: Uses same validation logic as in https://github.com/swiftmailer/swiftmailer/blob/5.x/lib/classes/Swift/Mime/Headers/MailboxHeader.php#L341

**Review by orthagh — APPROVED** [review]
